import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import ts from 'typescript';import assert from 'node:assert/strict';
mkdirSync('tests/generated',{recursive:true});
for(const name of ['departmentHistory','dataService'])writeFileSync(`tests/generated/${name}.mjs`,ts.transpileModule(readFileSync(`lib/${name}.ts`,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
const {departmentHistory:h}=await import('./generated/departmentHistory.mjs');const {seedState:s}=await import('./generated/dataService.mjs');
const job={...s.jobs[0],id:'j',jobNumber:'100',status:'In Production',currentDepartmentId:'print',updatedAt:'1999-01-01T00:00:00Z'};
const t=n=>new Date(Date.UTC(2026,9,1,8,n)).toISOString();
const event=(id,minute,departmentId,previousDepartmentId='',extra={})=>({id,jobId:'j',jobNumber:'100',departmentId,departmentName:departmentId,previousDepartmentId,timestamp:t(minute),type:'Normal',timestampBasis:'recorded',...extra});
const run=(events,j=job,archived=false)=>h(j,events,s.departments,s.statuses,Date.parse(t(120)),archived);
const events=[event('1',0,'print'),event('2',10,'print','print'),event('3',30,'lam','print'),event('4',60,'print','lam')];
let result=run([...events,events[0]]);assert.equal(result.eventCount,4);assert.deepEqual(result.visits.map(v=>v.departmentId),['print','lam','print']);assert.deepEqual(result.visits.map(v=>v.elapsedMs),[1800000,1800000,3600000]);assert.equal(result.visits[0].observations,2);assert.equal(result.visits[2].ongoing,true);
result=run([event('1',10,'print','print',{type:'Manual',statusName:'On Hold'})]);assert.equal(result.visits[0].arrival,undefined);assert.equal(result.visits[0].elapsedMs,undefined);
result=run([event('1',0,'print'),event('2',30,'print','print',{statusName:'Complete',statusClosesJob:true}),event('3',60,'print','print',{statusName:'In Production',statusClosesJob:false})]);assert.equal(result.visits.length,2);assert.equal(result.visits[0].elapsedMs,1800000);assert.equal(result.visits[1].arrival,t(60));
result=run([event('a',0,'print'),event('b',0,'lam'),event('c',60,'ship','lam')],{...job,currentDepartmentId:'ship'});assert.ok(result.warnings.some(w=>w.includes('unknown ordering')));assert.equal(result.visits[0].elapsedMs,undefined);assert.equal(result.visits[1].elapsedMs,undefined);
const split={...job,parts:[{id:'a',code:'100-A',name:'A',status:'In Production',currentDepartmentId:'lam'},{id:'b',code:'100-B',name:'B',status:'In Production',currentDepartmentId:'print'}]};
result=run([event('p',0,'prepress'),event('a1',10,'print','',{jobNumber:'100-A',partId:'a'}),event('a2',30,'lam','print',{jobNumber:'100-A',partId:'a'}),event('b1',20,'print','',{jobNumber:'100-B',partId:'b'})],split);assert.equal(result.visits.filter(v=>v.track==='100-A · A').length,2);assert.equal(result.visits.filter(v=>v.track==='100-B · B').length,1);assert.equal(result.visits.filter(v=>v.ongoing).length,2);
result=run(events,{...job,status:'Complete'},true);assert.equal(result.visits.at(-1).ongoing,false);assert.equal(result.visits.at(-1).departure,undefined);assert.equal(result.visits.at(-1).elapsedMs,undefined);
result=run([event('old',0,'print','',{jobNumber:'OLD'})]);assert.equal(result.visits[0].arrival,t(0));
result=run([event('bad',0,'print','',{timestamp:'invalid'})]);assert.ok(result.warnings.some(w=>w.includes('invalid')));
console.log('PASS: repeat visits; same-department duplicates; status changes preserve dwell; closure/reopening; ambiguous timestamp ties; independent parts; unknown arrivals/departures; no invented archive end; stable-ID rename; invalid timestamps; editable job clock ignored.');
