import {readFileSync} from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
let source=ts.transpileModule(readFileSync('src/IntakeParts.tsx','utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
source=source.replaceAll('"react/jsx-runtime"',JSON.stringify(import.meta.resolve('react/jsx-runtime')));
const {IntakeParts,initialParts}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const nodes=element=>Array.isArray(element)?element.flatMap(nodes):element&&typeof element==='object'?[element,...nodes(element.props?.children)]:[];
let parts=initialParts(),enabled=false;
const render=()=>nodes(IntakeParts({parts,enabled,jobNumber:'123456',onToggle:value=>enabled=value,onChange:value=>parts=value}));
assert.equal(render().filter(n=>n.type==='input').length,1);
render().find(n=>n.type==='input').props.onChange({target:{checked:true}});
assert.equal(enabled,true);
assert.equal(render().filter(n=>n.type==='input'&&n.props.required).length,2);
render().find(n=>n.props?.className==='add-create-part').props.onClick();
assert.equal(parts.length,3);
assert.equal(parts[2].name,'Part C');
render().find(n=>n.props?.['aria-label']==='Remove Part C').props.onClick();
assert.equal(parts.length,2);
assert.equal(render().some(n=>n.props?.['aria-label']==='Remove Part A'),false);
parts=Array.from({length:26},(_,i)=>({name:`Part ${i}`,description:'',quantity:''}));
assert.equal(render().find(n=>n.props?.className==='add-create-part').props.disabled,true);
assert.notEqual(initialParts(),initialParts());
console.log('PASS: split toggle, required names, add/remove parts, two-part minimum, 26-part limit, fresh reset defaults.');
