import { useEffect, useState } from "react";
import type { Department, Job, ScanEvent, StatusDefinition } from "../lib/dataService";
import { departmentHistory, elapsedDuration } from "../lib/departmentHistory";
export type HistoryLoader = () => Promise<ScanEvent[]>;
export function DepartmentHistory({job,departments,statuses,loadEvents,archived=false,captureStatus}:{job:Job;departments:Department[];statuses:StatusDefinition[];loadEvents:HistoryLoader;archived?:boolean;captureStatus?:string}) {
 const [open,setOpen]=useState(false);
 return <section className="department-data"><button type="button" className="secondary" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>Data / Department History {open?"−":"+"}</button>{open&&<HistoryContents job={job} departments={departments} statuses={statuses} loadEvents={loadEvents} archived={archived} captureStatus={captureStatus}/>}</section>;
}
function HistoryContents({job,departments,statuses,loadEvents,archived,captureStatus}:{job:Job;departments:Department[];statuses:StatusDefinition[];loadEvents:HistoryLoader;archived:boolean;captureStatus?:string}) {
 const [events,setEvents]=useState<ScanEvent[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [retry,setRetry]=useState(0);const [now,setNow]=useState(Date.now());
 useEffect(()=>{let active=true;setLoading(true);setError("");loadEvents().then(result=>{if(active){setEvents(result);setNow(Date.now());}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"History could not be loaded.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[loadEvents,retry]);
 useEffect(()=>{if(archived)return;const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[archived]);
 const result=departmentHistory(job,events,departments,statuses,now,archived);
 const format=(value:string|undefined)=>value?new Date(value).toLocaleString(undefined,{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit",timeZoneName:"short"}):"Unknown";
 return <div className="department-data-body"><h3>Department route</h3><p><b>Elapsed time includes waiting and queue time—not hands-on labor.</b> Times shown in {Intl.DateTimeFormat().resolvedOptions().timeZone}. No extra scans are required.</p>{archived&&captureStatus!=="complete"&&<p role="status">{captureStatus==="capturing"?"History capture is pending. The archive is not yet complete; retry capture from this record.":"This archive has no confirmed full-history capture."}</p>}{loading?<p role="status">Loading this job’s recorded events…</p>:error?<div role="alert">{error} <button type="button" onClick={()=>setRetry(value=>value+1)}>Retry history</button></div>:<><div className="history-data-summary"><span>{result.eventCount} recorded events loaded</span>{!archived&&<button type="button" className="secondary" onClick={()=>setRetry(value=>value+1)}>Refresh history</button>}</div>{result.warnings.map(warning=><p className="history-data-warning" key={warning}>{warning}</p>)}{!result.visits.length?<p>No department arrivals have been recorded. Missing times remain unknown.</p>:<><div className="department-route">{[...new Set(result.visits.map(visit=>visit.track))].map(track=><div key={track}><h4>{track}</h4><ol>{result.visits.filter(visit=>visit.track===track).map((visit,index)=><li key={index}><b>{visit.departmentName}</b><span>{elapsedDuration(visit.elapsedMs)}{visit.ongoing?" · Still here · ongoing":""}</span></li>)}</ol></div>)}</div><details className="history-scan-details"><summary>Show detailed scan-by-scan history</summary><h4>Department visit timings</h4><div className="department-history-table"><table><thead><tr><th>Job / Part</th><th>Department / Visit</th><th>Arrival</th><th>Departure / End</th><th>Elapsed</th></tr></thead><tbody>{result.visits.map((visit,index)=><tr key={`${visit.track}-${index}`}><td>{visit.track}</td><td><b>{visit.departmentName}</b><small>Visit {result.visits.slice(0,index+1).filter(item=>item.track===visit.track&&item.departmentId===visit.departmentId).length} · {visit.observations} observations</small>{visit.notes.map(note=><small key={note}>{note}</small>)}</td><td>{format(visit.arrival)}</td><td>{visit.ongoing?"Still here · ongoing":format(visit.departure)}</td><td><b>{elapsedDuration(visit.elapsedMs)}</b>{visit.ongoing&&<small>Updates every 30 seconds</small>}</td></tr>)}</tbody></table></div><h4>Recorded scans</h4><ol className="recorded-scans">{[...new Map(events.map(event=>[event.id,event])).values()].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)||a.id.localeCompare(b.id)).map(event=><li key={event.id}><time>{format(event.timestamp)}</time><b>{event.partCode||event.jobNumber}</b><span>{departments.find(item=>item.id===event.previousDepartmentId)?.name||"Unknown"} → {departments.find(item=>item.id===event.departmentId)?.name||event.departmentName}</span><small>{event.type}{event.statusName?` · ${event.statusName}`:""}</small></li>)}</ol></details></>}</>}</div>;
}
